# Generated by Django 5.2.17 on 2026-09-15 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_ingreso', models.DateField()),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('baja', 'Baja')], max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
