# Generated by Django 5.2.17 on 2026-09-15 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='carnet_colegiado',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='socio',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
