# Generated by Django 5.2.17 on 2026-09-17 02:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0002_socio_carnet_colegiado_socio_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='actividad_economica',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='socio',
            name='carrera',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='socio',
            name='direccion_habitacion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='socio',
            name='direccion_regional',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='socio',
            name='email_factura',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='socio',
            name='email_personal',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='socio',
            name='email_trabajo',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='socio',
            name='estado_civil',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='socio',
            name='fecha_ingreso_tesorero',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socio',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socio',
            name='nacionalidad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='socio',
            name='numero_circuitos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socio',
            name='telefono_fijo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='socio',
            name='telefono_oficina',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='socio',
            name='carnet_colegiado',
            field=models.CharField(default='SIN-CARNET', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='socio',
            name='estado',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='socio',
            name='fecha_ingreso',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
